-- 코드를 작성해주세요
SELECT GEN3.ID
FROM ECOLI_DATA GEN3
JOIN (
SELECT GEN2.ID
FROM (SELECT DISTINCT(ID) FROM ECOLI_DATA WHERE PARENT_ID IS NULL) GEN1
JOIN ECOLI_DATA GEN2
ON GEN1.ID = GEN2.PARENT_ID
) GEN2 ON GEN3.PARENT_ID = GEN2.ID
ORDER BY ID