-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, P.PRICE*SUM(O.AMOUNT) AS TOTAL_SALES
# SELECT SUM(O.AMOUNT)
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID 