-- 트럭의 대여 기록 별로 대여 금액 구하기
WITH T AS (SELECT C.CAR_ID, C.DAILY_FEE, H.HISTORY_ID,CAR_TYPE, DATEDIFF(END_DATE,START_DATE)+1 AS DURATION, 
          CASE
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >=90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >=30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >=7 THEN '7일 이상'
            ELSE 'None' END AS DURATION_TYPE
          FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          ON C.CAR_ID = H.CAR_ID 
          WHERE CAR_TYPE='트럭')
SELECT HISTORY_ID, ROUND(DAILY_FEE*((100-IFNULL(DISCOUNT_RATE,0))/100)*DURATION,0) AS FEE
# , DISCOUNT_RATE, P.DURATION_TYPE, DURATION
FROM T LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON T.DURATION_TYPE = P.DURATION_TYPE AND T.CAR_TYPE=P.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC